@startuml

title Diagrama de Casos de Uso

left to right direction
hide circles

actor Operario
actor RobotRPA
actor SAP
actor AdministradorSAP

rectangle "Sistema RPA Galia/SAP" {
    usecase "Registrar declaración" as UC1
    usecase "Guardar registro" as UC2
    usecase "Enviar a SAP" as UC4
    usecase "Procesar declaraciones" as UC5
    usecase "Cambiar contraseña automáticamente" as UC6
    usecase "Imprimir Galia" as UC7
    usecase "Desbloquear cuenta SAP" as UC8
}

Operario --> UC1
Operario --> UC2
Operario --> UC4

UC5 .> UC6 : <<include>>

RobotRPA --> UC5
SAP --> UC7
AdministradorSAP --> UC8

@enduml