@startuml
title CU4 Procesar Declaraciones

|ServidorEscucha|
start
:Activa RobotRPA;

|RobotRPA|
:Verifica días desde\núltimo cambio de contraseña;

if (¿Días >= 28?) then (sí)
    :Ejecuta UC5\nCambiar contraseña automáticamente;
    if (¿Cambio exitoso?) then (no)
        :Registra error crítico;
        stop
    endif
endif

:Se loguea en SAP con usuario\ndel puesto de trabajo;

if (¿Login correcto?) then (no)
    :Registra error crítico\nde credenciales;
    stop
else (sí)
    :Escribe y ejecuta\ntransacción en SAP;
endif

:Lee registros con estado = 0 de BD;

if (¿Hay registros pendientes?) then (no)
    :Cierra sesión en SAP;
    stop
else (sí)
endif

repeat

    |RobotRPA|
    :Toma siguiente registro\n[estado = 0];
    :Completa campos en SAP\n(referencia, orden, cantidad);

    |SAP|
    if (¿SAP procesa correctamente?) then (sí)
        :Envía Galia a impresora\ndel puesto;

        |RobotRPA|
        :Actualiza registro\n[estado = 1];
    else (no)
        |RobotRPA|
        :Actualiza registro\n[estado = 2];
    endif

repeat while (¿Quedan registros estado = 0?) is (sí)
->no;

:Cierra sesión en SAP;
stop

@enduml